name: flutter_tensor_flow
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tflite: ^1.1.2
  image: ^3.1.3
  image_picker: ^0.8.4+11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tflite/ssd_mobilenet.tflite
    - assets/tflite/ssd_mobilenet.txt
    - assets/tflite/yolov2_tiny.tflite
    - assets/tflite/yolov2_tiny.txt
